### ISSUE TITLE
Inquiring about abbreviation

### ISSUE THREAD

**Issue by teddythinh** [holarissun/PanelGPT#3]
Dear authors,

Thank you for your great work. I am just curious about the meaning of AE and EA in the table.

<img width="185" alt="image" src="https://github.com/holarissun/PanelGPT/assets/85171754/fd5cefdb-a88f-42fd-ac6a-97229d2c5d92">

**Comment by holarissun** [comment]
Thanks for your interest!

In some of the experiments, I misspelled the panel into penal. The results are also surprisingly good (better than baselines). I used the abbreviation EA to denote penal and AE to denote panel, and studied their effects in ablation studies.

Hope this helps :) 

Best,
Hao

**Comment by teddythinh** [comment]
Oh, I also surprisingly with this approach 😄 But I think you might write a little description for readers. Anyway, thank you for your work. It's helped me a lot 💯.
